name: Algolia Search

on:
  schedule:
  - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Run Scraper
    env:
      APPLICATION_ID: ${{secrets.APPLICATION_ID}}
      API_KEY: ${{secrets.ALGOLIA_API}}
      run: |
      brew install jq
      docker run -it -e "APPLICATION_ID=${{secrets.APPLICATION_ID}}" "API_KEY=${{secrets.ALGOLIA_API}}" "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper